import {pageMetadata} from '@/seo';
import KeywordGallery from '@/components/keyword-gallery';
import {busanKeywords,busanGallerySlot} from '@/busan-keywords';
import Link from 'next/link';import {notFound} from 'next/navigation';import type {Metadata} from 'next';import {busan} from '@/data';import {busanTopics} from '@/busan-topics';import {contactPhone,contactTel} from '@/contact';
export function generateStaticParams(){return busan.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=busan.find(x=>x.slug===slug);return pageMetadata({alternates:{canonical:`/busan/${slug}`},title:a?`부산 ${a.name} 고장난 노트북 현장매입`:'지역 안내',description:a?`부산 ${a.name} ${a.focus} 매입 상담. ${busanTopics[slug].intro}`:''})}
export default async function BusanArea({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=busan.find(x=>x.slug===slug);if(!a)notFound();const topic=busanTopics[slug];const areaIndex=busan.findIndex(x=>x.slug===slug);const nearby=[1,2,3,4].map(offset=>busan[(areaIndex+offset)%busan.length]);
const {fourth,related}=busanKeywords[slug];
const slot=busanGallerySlot(slug);
const gallery=<KeywordGallery pageKey={`busan-${slug}`} title={`${a.name} 기기 정리와 수거 상담 주제`} description="노트북 매입을 중심으로 안내합니다. 데스크톱 등 다른 컴퓨터는 종류와 상태를 먼저 알려주고 수거 가능 여부를 상담해 주세요." keywords={[`${a.name} 컴퓨터 수거 상담`,`${a.name} 노트북 수거 문의`,`${a.name} 고장난 노트북 수거`,`${a.name} ${fourth}`]} hrefs={[`/busan/${slug}#contact`,'/guide/model','/condition/scrap-laptop',related]} tags={[`${a.name} 매입 상담`,'모델·상태 확인','방문 가능 여부']}/>;
return <main className="shell inner-page"><div className="breadcrumbs"><Link href="/">홈</Link> / <Link href="/busan">부산 현장매입</Link> / {a.name}</div><div className="inner-hero"><span className="kicker">BUSAN · {a.name}</span><h1>{a.name} 고장난 노트북<br/><em>현장매입 안내</em></h1><p>{topic.intro} 방문 가능 여부와 일정은 제품 정보와 위치를 확인한 뒤 안내합니다.</p><div className="info-chip">⌖ {a.districts}</div></div>{slot===0&&gallery}<div className="detail-grid"><article className="detail-card"><span className="feature-icon">▤</span><h2>{a.name} 매입 상담 전 확인할 내용</h2><h3>{a.focus}</h3><p>{a.detail}</p></article><article className="detail-card"><span className="feature-icon">⌕</span><h2>현장매입 준비 순서</h2><ol><li>하판 라벨의 모델명과 기기 사진 확인</li><li>전원·화면·외관 상태 정리</li><li>방문 가능 여부 및 일정 상담</li><li>실물 점검 후 최종 조건 확인</li></ol></article></div>{topic&&<section className="area-topic"><div className="section-head"><span className="kicker">LOCAL GUIDE</span><h2>{topic.title}</h2></div><div className="detail-grid"><article className="detail-card"><h3>상담 전 확인 목록</h3><ul>{topic.checks.map(check=><li key={check}>{check}</li>)}</ul></article><article className="detail-card"><h3>{topic.question}</h3><p>{topic.answer}</p></article></div></section>}{slot===1&&gallery}<section className="content-panel"><h2>고장난 제품도 상담할 수 있나요?</h2><p>전원 불량, 액정 파손, 침수 등은 모델·연식·부품 상태에 따라 결과가 다릅니다. 고장 원인을 임의로 확정하지 말고 현재 나타나는 증상과 사진을 알려주세요. 매입 여부와 최종 금액은 실물 확인 후 결정됩니다.</p><div className="inline-links"><Link href="/condition/no-power">전원 불량 안내 ↗</Link><Link href="/condition/broken-screen">액정 파손 안내 ↗</Link><Link href="/condition/water-damage">침수 안내 ↗</Link></div></section>{slot===2&&gallery}<div className="notice-box"><strong>개인정보를 먼저 정리하세요</strong><p>중요 파일을 백업하고 기기 계정을 로그아웃하세요. 초기화가 어려운 고장 기기는 저장장치 처리 방법을 상담 과정에서 확인해 주세요.</p></div><div className="local-cta" id="contact"><div><strong>{a.name} 노트북 현장매입 상담</strong><span>모델과 상태를 알려주시면 방문 가능 여부와 절차를 안내합니다.</span></div><a href={contactTel}>전화 상담 {contactPhone} ↗</a></div><div className="section-head"><h2>다른 부산 지역</h2></div><div className="ship-pills">{nearby.map(x=><Link href={`/busan/${x.slug}`} key={x.slug}>{x.name} ↗</Link>)}<Link href="/busan">전체 지역 →</Link></div></main>}
