import {pageMetadata} from '@/seo';
import KeywordGallery from '@/components/keyword-gallery';
import {regionKeywords,regionGallerySlot} from '@/region-keywords';
import ShippingAddress from '@/components/shipping-address';
import {localFor} from '@/local-areas';
import Link from 'next/link';import {notFound} from 'next/navigation';import type {Metadata} from 'next';import {shipping} from '@/data';import {regionTopics} from '@/region-topics';import {contactPhone,contactTel} from '@/contact';
export function generateStaticParams(){return shipping.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=shipping.find(x=>x.slug===slug);return pageMetadata({alternates:{canonical:`/regions/${slug}`},title:a?`${a.name} 고장난 노트북 택배매입`:'지역 안내',description:a?`${a.name} 노트북 택배매입. ${regionTopics[slug].intro}`:''})}
export default async function Region({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=shipping.find(x=>x.slug===slug);if(!a)notFound();const children=localFor(slug);const topic=regionTopics[slug];
const {fourth,related}=regionKeywords[slug];
const slot=regionGallerySlot(slug);
const gallery=<KeywordGallery pageKey={`region-${slug}`} title={`${a.name} 노트북 택배매입 주제`} description="사진과 기기 상태로 먼저 상담한 뒤 발송 조건을 확인해 주세요." keywords={[`${a.name} 노트북 택배매입`,`${a.name} 폐 노트북 발송 상담`,`${a.name} 고장난 노트북 택배`,`${a.name} ${fourth}`]} hrefs={[`/regions/${slug}#contact`,'/guide/packing','/condition/scrap-laptop',related]} tags={[`${a.name} 택배매입`,'발송 전 상담','실물 확인']}/>;
return <main className="shell inner-page"><div className="breadcrumbs"><Link href="/">홈</Link> / <Link href="/regions">전국 택배매입</Link> / {a.name}</div><div className="inner-hero violet"><span className="kicker">DELIVERY · {a.name}</span><h1>{a.name} 고장난 노트북<br/><em>택배매입 안내</em></h1><p>{topic.intro}</p><div className="info-chip">▣ {a.districts}</div></div>{slot===0&&gallery}<ShippingAddress/><div className="detail-grid"><article className="detail-card"><span className="feature-icon">▤</span><h2>{a.name} 접수 포인트</h2><h3>{a.focus}</h3><p>{a.detail}</p></article><article className="detail-card"><span className="feature-icon">▣</span><h2>택배매입 진행 순서</h2><ol><li>모델명·사진·고장 상태 확인</li><li>발송 가능 여부와 조건 상담</li><li>기기 백업 및 안전 포장 후 발송</li><li>실물 점검 후 최종 매입 조건 안내</li></ol></article></div>{slot===1&&gallery}{topic&&<section className="area-topic"><div className="section-head"><span className="kicker">SHIPPING GUIDE</span><h2>{topic.title}</h2></div><div className="detail-grid"><article className="detail-card"><h3>발송 전 확인 목록</h3><ul>{topic.checks.map(check=><li key={check}>{check}</li>)}</ul></article><article className="detail-card"><h3>{topic.question}</h3><p>{topic.answer}</p></article></div></section>}<section className="content-panel"><h2>파손된 노트북 포장 방법</h2><p>전원을 끄고 기기를 부드러운 완충재로 감싸 주세요. 화면과 모서리를 보호하고 상자 안에서 본체가 움직이지 않도록 빈 공간을 채웁니다. 침수 기기는 전원을 다시 켜지 말고 상태를 먼저 알려주세요.</p></section>{children.length>0&&<section className="local-list"><div className="section-head"><span className="kicker">LOCAL AREAS</span><h2>{a.name} 세부 지역 안내</h2><p>지역마다 접수 전에 확인할 주제를 골라 살펴보세요.</p></div><div className="local-list-grid">{children.map(child=><Link href={`/regions/${slug}/${child.slug}`} key={child.slug}><span>▣</span><strong>{child.name} 노트북 택배매입</strong><small>{child.topic}</small><b>자세히 보기 ↗</b></Link>)}</div></section>}{slot===2&&gallery}<div className="notice-box"><strong>검수 전 확인</strong><p>중요 자료를 백업하고 계정을 로그아웃해 주세요. 사전 상담 내용과 실물 상태가 다르면 최종 조건이 달라질 수 있습니다.</p></div><div className="local-cta" id="contact"><div><strong>{a.name} 노트북 택배매입 상담</strong><span>발송 전에 모델과 상태를 알려주고 접수 조건을 확인하세요.</span></div><a href={contactTel}>전화 상담 {contactPhone} ↗</a></div><div className="inline-links"><Link href="/regions">다른 지역 보기 →</Link><Link href="/condition/no-power">전원 불량 안내 ↗</Link><Link href="/condition/broken-screen">액정 파손 안내 ↗</Link></div></main>}
