import Link from 'next/link';
import type {Metadata} from 'next';
export const metadata:Metadata={
  title:'고장난 노트북·폐 노트북 매입',
  description:'전원 불량, 액정 파손, 침수 등 고장난 노트북과 폐 노트북의 매입 가능 여부를 상담합니다. 부산은 현장매입, 전국은 택배매입으로 안내합니다.',
  alternates:{canonical:'/'},
};
import {busan,shipping,conditions} from '@/data';
import QuickCheck from '@/components/quick-check';
import AppIcon from '@/components/app-icon';
import ContactPanel from '@/components/contact-panel';

const conditionIcons={
  'no-power':'power','broken-screen':'screen','water-damage':'water',
  battery:'battery',keyboard:'keyboard','old-laptop':'laptop','scrap-laptop':'laptop'
} as const;

export default function Home(){return <main>
  <section className="hero shell"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> 중고·고장 노트북 매입 안내</div><h1>고장난 노트북<br/><em>(폐 노트북) 매입합니다.</em></h1><p>전원이 안 켜져도, 화면이 깨졌어도 괜찮습니다.<br/>모델과 상태에 맞춰 매입 가능 여부를 확인해 드립니다.</p><div className="hero-actions"><Link className="button primary" href="#estimate">내 노트북 확인하기 <span>↗</span></Link><Link className="button light" href="#how">매입 방법 보기</Link></div><div className="hero-trust"><span>✓ 고장 제품 상담</span><span>✓ 지역별 접수 방식</span><span>✓ 상태 확인 후 안내</span></div></div><div className="hero-art" aria-label="노트북 매입 방식 안내"><div className="orb orb-one"/><div className="orb orb-two"/><div className="laptop"><div className="screen"><div className="screen-check">✓</div><strong>다시 쓰는 가치</strong><span>올바른 매입</span></div><div className="keyboard"/></div><div className="float-card card-top"><span>⚡</span><div><b>고장난 노트북도</b><small>상태별로 확인해요</small></div></div><div className="float-card card-bottom"><span>✓</span><div><b>내 노트북은?</b><small>간편하게 매입 상담</small></div></div></div></section>
  <section className="shell routes" id="how"><div className="section-head"><div><span className="kicker">HOW TO SELL</span><h2>어디서든, 내게 맞는 방법으로</h2><p>부산은 현장 방문, 다른 지역은 택배로 접수합니다.</p></div></div><div className="route-grid"><Link href="/busan" className="route-card busan-card"><div className="route-icon"><AppIcon name="location" size={30}/></div><div><span className="route-label">BUSAN · ON SITE</span><h3>부산 현장매입</h3><p>부산 16개 구·군에서 방문 가능 여부와 일정을 상담해요.</p><span className="text-link">지역 살펴보기 <b>↗</b></span></div></Link><Link href="/regions" className="route-card shipping-card"><div className="route-icon"><AppIcon name="package" size={30}/></div><div><span className="route-label">NATIONWIDE · DELIVERY</span><h3>전국 택배매입</h3><p>부산 외 지역은 사진으로 먼저 확인하고 택배로 접수해요.</p><span className="text-link">택배 절차 보기 <b>↗</b></span></div></Link></div></section>
  <section className="soft-section" id="conditions"><div className="shell"><div className="section-head split"><div><span className="kicker">WHAT WE BUY</span><h2>이런 상태도 문의해 보세요</h2><p>고장 증상을 선택하면 확인할 내용을 자세히 볼 수 있어요.</p></div><span className="section-aside">최종 매입 가능 여부는 제품 확인 후 결정됩니다.</span></div><div className="condition-grid">{conditions.map(c=><Link href={`/condition/${c.slug}`} className="condition-card" key={c.slug}><span className="condition-icon"><AppIcon name={conditionIcons[c.slug as keyof typeof conditionIcons]}/></span><strong>{c.title}</strong><small>{c.text}</small><span className="arrow">↗</span></Link>)}</div></div></section>
  <section className="shell estimate" id="estimate"><div className="estimate-copy"><span className="kicker">QUICK CHECK</span><h2>상담 전에 내 노트북<br/><em>정보를 정리해 보세요</em></h2><p>모델과 상태를 선택하면 상담에 필요한 내용을 한 번에 정리할 수 있습니다.</p><div className="estimate-tip">💡 모델명을 모르시면 노트북 바닥면의 라벨을 촬영해 두세요.</div></div><QuickCheck/></section>
  <section className="shell region-section"><div className="section-head split"><div><span className="kicker">FIND YOUR AREA</span><h2>내 지역 매입 방식 찾기</h2><p>지역을 선택하면 접수 방법과 준비할 정보를 확인할 수 있어요.</p></div><Link href="/regions" className="more-link">전국 지역 보기 ↗</Link></div><div className="region-preview"><div className="preview-heading"><span><AppIcon name="location" size={25}/></span><div><strong>부산 현장매입</strong><small>방문 가능 여부·일정은 상담 후 안내</small></div></div><div className="pill-grid">{busan.slice(0,8).map(a=><Link href={`/busan/${a.slug}`} key={a.slug}>{a.name}<span>↗</span></Link>)}</div><Link className="preview-all" href="/busan">부산 16개 구·군 모두 보기 →</Link></div><div className="ship-pills">{shipping.slice(0,7).map(a=><Link href={`/regions/${a.slug}`} key={a.slug}>{a.name} <span>↗</span></Link>)}</div></section>
  <section className="process-section" id="process"><div className="shell"><div className="section-head"><div><span className="kicker">SIMPLE PROCESS</span><h2>매입은 이렇게 진행돼요</h2><p>발송하거나 방문 일정을 잡기 전에 먼저 제품 정보를 확인합니다.</p></div></div><div className="steps"><div><span className="step-icon"><AppIcon name="list"/></span><small>STEP 01</small><strong>제품 정보 확인</strong><p>모델명, 사진, 고장 증상을 준비합니다.</p></div><div><span className="step-icon"><AppIcon name="package"/></span><small>STEP 02</small><strong>방식과 조건 상담</strong><p>부산 방문 또는 전국 택배 절차를 안내받습니다.</p></div><div><span className="step-icon"><AppIcon name="search"/></span><small>STEP 03</small><strong>실물 상태 확인</strong><p>실제 기기 상태와 구성품을 점검합니다.</p></div><div><span className="step-icon"><AppIcon name="check"/></span><small>STEP 04</small><strong>최종 금액 안내</strong><p>확인 결과를 바탕으로 매입 여부를 결정합니다.</p></div></div></div></section>
  <section className="shell guide-promo"><div><span className="kicker">BUYING GUIDE</span><h2>판매 전 궁금한 점을 확인하세요</h2><p>가격 판단 기준, 개인정보 정리, 택배 포장 방법을 정리했습니다.</p></div><Link className="button light" href="/guide">매입 가이드 보기 ↗</Link></section>
  <ContactPanel/>
  <section className="shell final-banner"><div><span>OLBAREUN BUY</span><h2>서랍 속 노트북,<br/>지금 상태부터 확인해 보세요.</h2><p>정상 제품부터 고장난 노트북까지, 지역별 안내를 확인하세요.</p></div><div className="banner-buttons"><Link href="/busan">부산 현장매입 ↗</Link><Link href="/regions">전국 택배매입 ↗</Link></div></section>
 </main>}
