import Image from 'next/image';
import CopyShippingAddress from '@/components/copy-shipping-address';
import KeywordGallery from '@/components/keyword-gallery';
import Link from 'next/link';
import type {Metadata} from 'next';
export const metadata:Metadata={
  title:'고장난 노트북·폐 노트북 매입',
  description:'전원 불량, 액정 파손, 침수 등 고장난 노트북과 폐 노트북의 매입 가능 여부를 상담합니다. 부산은 현장매입, 전국은 택배매입으로 안내합니다.',
  alternates:{canonical:'/'},
};
import {busan,shipping,conditions} from '@/data';
import QuickCheck from '@/components/quick-check';
import AppIcon from '@/components/app-icon';
import ContactPanel from '@/components/contact-panel';
import {brands} from '@/brands';

const conditionIcons={
  'no-power':'power','broken-screen':'screen','water-damage':'water',
  battery:'battery',keyboard:'keyboard','old-laptop':'laptop','scrap-laptop':'laptop'
} as const;

export default function Home(){return <main>
  <section className="hero-photo"><Image className="hero-background-image" src="/uploads/hero-laptop.png" alt="" fill priority sizes="100vw"/><div className="hero shell"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> 중고·고장 노트북 매입 안내</div><h1>고장난 노트북<br/><em>(폐 노트북) 매입합니다.</em></h1><p>전원이 안 켜져도, 화면이 깨졌어도 괜찮습니다.<br/>모델과 상태에 맞춰 매입 가능 여부를 확인해 드립니다.</p><div className="hero-actions"><Link className="button primary" href="#estimate">내 노트북 확인하기 <span>↗</span></Link><Link className="button light" href="#how">매입 방법 보기</Link></div><div className="hero-contact"><a className="hero-contact-phone" href="tel:01066484886"><span className="hero-contact-icon"><AppIcon name="phone" size={22}/></span><span><small>전화번호</small><strong>010-6648-4886</strong></span></a><div className="hero-contact-kakao"><span className="hero-contact-icon"><svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 3C6.5 3 2 6.4 2 10.6c0 2.7 1.8 5.1 4.6 6.4l-1.1 4 4.6-2.9c.6.1 1.2.1 1.9.1 5.5 0 10-3.4 10-7.6S17.5 3 12 3Z"/></svg></span><span><small>카톡 ID</small><strong>mx4885</strong></span></div></div><div className="hero-trust"><span>✓ 고장 제품 상담</span><span>✓ 지역별 접수 방식</span><span>✓ 상태 확인 후 안내</span></div></div></div></section>
  <section className="shell routes" id="how"><div className="section-head"><div><span className="kicker">HOW TO SELL</span><h2>어디서든, 내게 맞는 방법으로</h2><p>부산은 현장 방문, 다른 지역은 택배로 접수합니다.</p></div></div><div className="route-grid"><div className="route-card busan-card busan-home-card"><div className="route-icon"><AppIcon name="location" size={30}/></div><div><span className="route-label">BUSAN · ON SITE</span><h3>부산 현장매입</h3><p>부산 16개 구·군에서 방문 가능 여부와 일정을 상담해요.</p><Link href="/busan" className="text-link">지역 살펴보기 <b>↗</b></Link></div><div className="busan-home-areas">{busan.slice(0,8).map(area=><Link href={`/busan/${area.slug}`} key={area.slug}>{area.name}<span aria-hidden="true">↗</span></Link>)}</div></div><div className="route-card shipping-card shipping-contact-card"><div className="route-icon"><AppIcon name="package" size={30}/></div><div className="shipping-card-body"><div className="shipping-card-intro"><span className="route-label">NATIONWIDE · DELIVERY</span><h3>전국 택배매입</h3><p>부산 외 지역은 사진으로 먼저 확인하고 택배로 접수해요.</p><div className="shipping-collect-notice">택배는 <strong>착불</strong>로 보내주세요</div></div><div className="shipping-address"><span><AppIcon name="location" size={17}/> 택배 보내실 주소</span><address>부산광역시 부산진구<br/>백양대로252번길 14<br/>(개금동) 1층 올바른 매입<br/><a href="tel:01066484886">T.010-6648-4886</a></address><small>우편번호 47172 · 수취인 올바른매입</small><CopyShippingAddress/></div><Link href="/regions" className="text-link">택배 절차 보기 <b>↗</b></Link><div className="shipping-kakao"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 3C6.5 3 2 6.4 2 10.6c0 2.7 1.8 5.1 4.6 6.4l-1.1 4 4.6-2.9c.6.1 1.2.1 1.9.1 5.5 0 10-3.4 10-7.6S17.5 3 12 3Z"/></svg> 카톡 문의 <strong>mx4885</strong></div></div></div></div></section>
  <section className="soft-section" id="conditions"><div className="shell"><div className="section-head split"><div><span className="kicker">WHAT WE BUY</span><h2>이런 상태도 문의해 보세요</h2><p>고장 증상을 선택하면 확인할 내용을 자세히 볼 수 있어요.</p></div><span className="section-aside">최종 매입 가능 여부는 제품 확인 후 결정됩니다.</span></div><div className="condition-grid">{conditions.map(c=><Link href={`/condition/${c.slug}`} className="condition-card" key={c.slug}><span className="condition-icon"><AppIcon name={conditionIcons[c.slug as keyof typeof conditionIcons]}/></span><strong>{c.title}</strong><small>{c.text}</small><span className="arrow">↗</span></Link>)}</div></div></section>
  <section className="shell brand-section"><div className="section-head"><span className="kicker">BRAND GUIDE</span><h2>제조사별로 확인해 보세요</h2><p>모델 확인과 계정 정리 방법을 브랜드별로 안내합니다.</p></div><div className="brand-grid">{brands.map(brand=><Link className="brand-card" href={`/brand/${brand.slug}`} key={brand.slug}><span className="brand-icon" aria-hidden="true">{brand.logoPath?<Image src={brand.logoPath} alt="" width={50} height={50}/>:brand.mark}</span><strong>{brand.name}</strong><small>매입 준비 방법 보기</small><b aria-hidden="true">↗</b></Link>)}</div></section>
  <section className="shell estimate" id="estimate"><div className="estimate-copy"><span className="kicker">QUICK CHECK</span><h2>상담 전에 내 노트북<br/><em>정보를 정리해 보세요</em></h2><p>모델과 상태를 선택하면 상담에 필요한 내용을 한 번에 정리할 수 있습니다.</p><div className="estimate-tip">💡 모델명을 모르시면 노트북 바닥면의 라벨을 촬영해 두세요.</div></div><QuickCheck/></section>
  <section className="shell region-section"><div className="section-head split"><div><span className="kicker">FIND YOUR AREA</span><h2>내 지역 매입 방식 찾기</h2><p>지역을 선택하면 접수 방법과 준비할 정보를 확인할 수 있어요.</p></div><Link href="/regions" className="more-link">전국 지역 보기 ↗</Link></div><div className="region-preview"><div className="preview-heading"><span><AppIcon name="location" size={25}/></span><div><strong>부산 현장매입</strong><small>방문 가능 여부·일정은 상담 후 안내</small></div></div><div className="pill-grid">{busan.slice(0,8).map(a=><Link href={`/busan/${a.slug}`} key={a.slug}>{a.name}<span>↗</span></Link>)}</div><Link className="preview-all" href="/busan">부산 16개 구·군 모두 보기 →</Link></div><div className="ship-pills">{shipping.slice(0,7).map(a=><Link href={`/regions/${a.slug}`} key={a.slug}>{a.name} <span>↗</span></Link>)}</div></section>
  <section className="process-section" id="process"><div className="shell"><div className="section-head"><div><span className="kicker">SIMPLE PROCESS</span><h2>매입은 이렇게 진행돼요</h2><p>발송하거나 방문 일정을 잡기 전에 먼저 제품 정보를 확인합니다.</p></div></div><div className="steps"><div><span className="step-icon"><AppIcon name="list"/></span><small>STEP 01</small><strong>제품 정보 확인</strong><p>모델명, 사진, 고장 증상을 준비합니다.</p></div><div><span className="step-icon"><AppIcon name="package"/></span><small>STEP 02</small><strong>방식과 조건 상담</strong><p>부산 방문 또는 전국 택배 절차를 안내받습니다.</p></div><div><span className="step-icon"><AppIcon name="search"/></span><small>STEP 03</small><strong>실물 상태 확인</strong><p>실제 기기 상태와 구성품을 점검합니다.</p></div><div><span className="step-icon"><AppIcon name="check"/></span><small>STEP 04</small><strong>최종 금액 안내</strong><p>확인 결과를 바탕으로 매입 여부를 결정합니다.</p></div></div></div></section>
  <section className="shell guide-promo"><div><span className="kicker">BUYING GUIDE</span><h2>판매 전 궁금한 점을 확인하세요</h2><p>가격 판단 기준, 개인정보 정리, 택배 포장 방법을 정리했습니다.</p></div><Link className="button light" href="/guide">매입 가이드 보기 ↗</Link></section>
  <ContactPanel/>
  <section className="shell final-banner"><div><span>OLBAREUN BUY</span><h2>서랍 속 노트북,<br/>지금 상태부터 확인해 보세요.</h2><p>정상 제품부터 고장난 노트북까지, 지역별 안내를 확인하세요.</p></div><div className="banner-buttons"><Link href="/busan">부산 현장매입 ↗</Link><Link href="/regions">전국 택배매입 ↗</Link></div></section>
  <div className="shell home-keywords"><KeywordGallery pageKey="home" title="노트북 매입 전 확인할 4가지" keywords={["고장난 노트북 매입","폐 노트북 상태 확인","부산 노트북 현장매입","전국 노트북 택배매입"]} hrefs={["/#conditions","/condition/scrap-laptop","/busan","/regions"]} tags={["모델 확인","고장 상태","매입 상담"]}/></div>
 </main>}
