import Link from 'next/link';import {notFound} from 'next/navigation';import type {Metadata} from 'next';
const articles={
  price:{title:'노트북 매입 가격이 결정되는 기준',lead:'같은 브랜드라도 모델과 상태에 따라 매입 조건이 달라집니다. 금액을 예측하기 전에 확인할 요소를 정리했습니다.',sections:[['모델과 사양','모델명, 출시 시기, CPU, 메모리, 저장장치, 그래픽 성능을 확인합니다. 같은 제품군에도 사양 차이가 있으므로 정확한 모델명이 중요합니다.'],['작동과 고장 상태','전원, 화면, 키보드, 배터리, 포트와 외관을 살펴봅니다. 고장 증상만으로 원인을 단정하기 어려워 실물 확인이 필요합니다.'],['구성품과 최종 확인','충전기 등 구성품 유무와 실제 제품 상태가 사전 안내와 일치하는지 확인합니다. 최종 매입 여부와 금액은 점검 후 안내됩니다.']]},
  privacy:{title:'노트북을 팔기 전 개인정보 정리',lead:'노트북에는 로그인 정보와 사진, 업무 자료가 남아 있을 수 있습니다. 기기를 넘기기 전에 직접 확인해 주세요.',sections:[['필요한 파일 백업','문서, 사진, 브라우저 북마크, 프로그램 설정 중 필요한 자료를 별도 저장장치나 본인 계정에 백업하고 실제로 열리는지 확인합니다.'],['계정 로그아웃','운영체제 계정과 클라우드 동기화, 브라우저 계정, 기기 찾기·잠금 기능을 확인합니다. 특히 기기와 연결된 계정 해제는 소유자가 직접 처리해야 합니다.'],['초기화와 고장 기기','정상 작동하는 기기는 제조사 또는 운영체제의 공식 초기화 절차를 따르세요. 전원이 켜지지 않는 제품은 저장장치 처리 방식을 먼저 상담하고, 민감한 정보가 남아 있다면 발송 전 별도로 결정하세요.']]},
  packing:{title:'노트북 택배매입 포장 방법',lead:'부산 외 지역에서 택배로 접수할 때는 상담 후 발송하고, 운송 중 제품이 움직이지 않도록 포장해 주세요.',sections:[['발송 전 기록','모델명과 외관, 고장 부위를 사진으로 남기고 충전기 등 동봉할 구성품을 확인합니다. 발송 조건을 먼저 안내받으세요.'],['본체 보호','전원을 끄고 화면 사이에 이물질이 없는지 확인합니다. 부드러운 완충재로 본체를 감싸고 모서리와 화면을 보호하세요. 파손된 유리 부분은 다치지 않게 주의합니다.'],['상자 안 고정','제품보다 여유 있는 단단한 상자를 사용하고 빈 공간을 완충재로 채워 흔들리지 않게 합니다. 충전기는 본체에 직접 닿지 않도록 따로 감싸 주세요. 침수 기기는 다시 전원을 켜지 말고 상태를 먼저 알려주세요.']]}
} as const;
export function generateStaticParams(){return Object.keys(articles).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=articles[slug as keyof typeof articles];return {alternates:{canonical:`/guide/${slug}`},title:a?.title||'매입 가이드',description:a?.lead||''}}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=articles[slug as keyof typeof articles];if(!a)notFound();return <main className="shell inner-page"><div className="breadcrumbs"><Link href="/">홈</Link> / <Link href="/guide">매입 가이드</Link> / {a.title}</div><div className="inner-hero"><span className="kicker">BUYING GUIDE</span><h1>{a.title}</h1><p>{a.lead}</p></div><div className="article-stack">{a.sections.map(([title,text],i)=><section className="content-panel" key={title}><span className="kicker">0{i+1}</span><h2>{title}</h2><p>{text}</p></section>)}</div><div className="notice-box"><strong>상담 전 준비</strong><p>모델명, 기기 사진, 현재 증상, 충전기 유무를 정리해 주세요. 매입 조건은 실물 확인 후 결정됩니다.</p></div><div className="inline-links"><Link href="/#estimate">노트북 정보 정리하기 ↗</Link><Link href="/busan">부산 현장매입 ↗</Link><Link href="/regions">전국 택배매입 ↗</Link></div></main>}
